name: chan
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.9+106 # Remember to update version.dart

environment:
  sdk: ">=3.3.0 <4.0.0"

publish_to: none
dependencies:
  media_kit: ^1.1.3
  media_kit_video: ^1.1.3
  media_kit_libs_ios_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/ios/media_kit_libs_ios_video_encoders_gpl
  media_kit_libs_macos_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/macos/media_kit_libs_macos_video_encoders_gpl
  media_kit_libs_android_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/android/media_kit_libs_android_video_encoders_gpl
  media_kit_libs_windows_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/windows/media_kit_libs_windows_video_encoders_gpl
  dio: ^4.0.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  html: ^0.15.0
  provider: ^6.0.0
  extended_image: ^6.0.1
  html_unescape: ^2.0.0
  share_plus: ^10.0.1
  extended_image_library: ^3.3.0
  flutter_inappwebview: ^6.0.0-beta.24+1
  home_indicator:
    git:
      url: https://github.com/moffatman/flutter_home_indicator
      ref: master
  linkify: ^4.1.0
  auto_size_text: ^3.0.0
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  heic_to_jpg: ^0.2.0
  mutex: ^3.0.0
  uuid: ^3.0.5
  profanity_filter: ^2.0.0
  url_launcher: ^6.0.12
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  google_fonts: ^4.0.3
  file_picker:
    git:
      url: https://github.com/moffatman/flutter_file_picker
      ref: master
  flutter_colorpicker: ^1.1.0
  photo_manager: ^3.1.1
  flutter_tex: ^4.0.3+4
  app_links: ^6.2.0
  crypto: ^3.0.1
  fluttertoast: ^8.2.1
  test: ^1.20.1
  flutter_exif_rotation:
    git:
      url: https://github.com/moffatman/flutter_exif_rotation
      ref: master
  normal: ^0.6.0
  pool: ^1.5.0
  connectivity_plus: ^4.0.2
  receive_sharing_intent:
    git:
      url: https://github.com/moffatman/receive_sharing_intent
      ref: master
  native_drag_n_drop:
    git:
      url: https://github.com/moffatman/FlutterNativeDragAndDrop
      ref: main
  mime: ^1.0.2
  http_parser: ^4.0.0
  cupertino_icons: ^1.0.0
  firebase_core: ^3.5.0
  unifiedpush: ^6.0.2
  flutter_apns_only: ^1.6.0
  flutter_local_notifications: ^17.2.1+2
  path_provider: ^2.0.10
  path_provider_ios: ^2.0.11
  async: ^2.9.0
  flutter_email_sender: ^6.0.3
  dynamic_color: ^1.5.2
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.1.2
  charset_converter: ^2.3.0
  markdown: ^7.2.1
  string_similarity: ^2.0.0
  weak_map: ^2.1.0
  vector_math: ^2.1.4
  local_auth: ^2.1.6
  screenshot: ^3.0.0
  ffi: ^2.0.2
  archive: ^3.6.1
  isolate_pool_2: ^1.0.7
  dio_http2_adapter: ^2.0.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  adaptive_icon_background: "assets/appicon_bg.png"
  adaptive_icon_foreground: "assets/appicon_fg.png"
  adaptive_icon_monochrome: "assets/appicon_monochrome.png"

flutter_native_splash:
  color: "#141414"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash_android12.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/katex.html
    - assets/splash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Submona
      fonts:
        - asset: assets/submona.ttf
dependency_overrides:
  heic_to_jpg:
    git:
      url: https://github.com/Hurricane472/flutter_heic_to_jpg.git
      ref: main
  extended_image:
    git:
      url: https://github.com/moffatman/extended_image.git
      ref: chan_master
  extended_image_library:
    git:
      url: https://github.com/moffatman/extended_image_library.git
  dio:
    git:
      url: https://github.com/moffatman/dio.git
      path: dio
      ref: develop
  markdown: ^7.2.1 # Needed to resolve a conflict with flutter_tex
  web: ^0.5.1 # Needed to run with current moffatman/flutter tag
  connectivity_plus: # Needed to prioritize Mobile over VPN on Android
    git:
      url: https://github.com/moffatman/plus_plugins.git
      ref: check_mobile_first
      path: packages/connectivity_plus/connectivity_plus
  flutter_inappwebview:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
  flutter_inappwebview_android:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_android
  flutter_inappwebview_ios:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
  flutter_inappwebview_macos:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
  flutter_inappwebview_platform_interface:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_platform_interface
  flutter_inappwebview_web:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_web
  flutter_inappwebview_windows:
    git:
      url: https://github.com/moffatman/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_windows
  media_kit:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: media_kit_video
  hive:
    git:
      url: https://github.com/moffatman/hive.git
      ref: master
      path: hive
  hive_generator:
    git:
      url: https://github.com/moffatman/hive.git
      ref: master
      path: hive_generator
  html:
    git:
      url: https://github.com/moffatman/dart-tools.git
      ref: main
      path: pkgs/html
  charset_converter:
    git:
      url: https://github.com/Hurricane472/charset_converter.git
      ref: master
  dio_http2_adapter:
    git:
      url: https://github.com/moffatman/dio.git
      path: plugins/http2_adapter
  unifiedpush_android:
    git:
      url: https://github.com/Hurricane472/unifiedpush_android.git
  analyzer: ^6.7.0
  dart_style: ^2.3.6
  js: ^0.7.1 # Needed to run with current connectivity_plus tag
