name: chan
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  ffmpeg_kit_flutter_full_gpl: ^4.5.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  html: ^0.15.0
  video_player: ^2.2.0
  rxdart: ^0.27.1
  provider: ^6.0.0
  extended_image: ^6.0.1
  html_unescape: ^2.0.0
  share_plus: ^4.0.4
  share_extend: "^2.0.0"
  extended_image_library: ^3.3.0
  flutter_inappwebview: ^5.2.1
  home_indicator: ^2.0.0
  linkify: ^4.1.0
  auto_size_text: ^3.0.0
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  image: ^3.0.4
  image_picker: ^0.8.4
  heic_to_jpg: ^0.2.0
  mutex: ^3.0.0
  tuple: ^2.0.0
  uuid: ^3.0.5
  profanity_filter: ^2.0.0
  url_launcher: ^6.0.12
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  google_fonts: ^2.1.0
  file_picker: ^4.2.3
  flutter_colorpicker: ^1.0.3
  photo_manager: ^2.0.0-dev.6
  flutter_tex: ^4.0.3+4
  uni_links: ^0.5.1
  crypto: ^3.0.1
  fluttertoast: ^8.0.8
  test: ^1.20.1
  flutter_exif_rotation: ^0.5.0
  normal: ^0.6.0
  pool: ^1.5.0
  connectivity_plus: ^2.3.0
  receive_sharing_intent:
    git: 
        url: https://github.com/krabbenprgr/receive_sharing_intent
  native_drag_n_drop: ^0.0.4
  mime: ^1.0.2
  http_parser: ^4.0.0
  cupertino_icons: ^1.0.0
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.14
  path_provider: ^2.0.10
  async: ^2.9.0
  flutter_email_sender: ^5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  adaptive_icon_background: "assets/appicon_bg.png"
  adaptive_icon_foreground: "assets/appicon_fg.png"

flutter_native_splash:
  color: "#141414"
  image: "assets/splash.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/katex.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
dependency_overrides:
  extended_image:
    git:
      url: https://github.com/moffatman/extended_image.git
      ref: master
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/moffatman/ffmpeg-kit.git
      ref: full_gpl_temp
      path: flutter/flutter/
  dio:
    git:
      url: https://github.com/moffatman/dio.git
      path: dio