class CountryFlag {
	final String code;
	final String name;
	final String emoji;
	const CountryFlag(this.code, this.name, this.emoji);

	@override
	bool operator == (Object other) =>
		identical(this, other) ||
		other is CountryFlag &&
		other.code == code &&
		other.name == name &&
		other.emoji == emoji;

	@override
	int get hashCode => code.hashCode;
}

const kCountries = {
	'AC': CountryFlag('AC', 'Ascension Island', '🇦🇨'),
	'AD': CountryFlag('AD', 'Andorra', '🇦🇩'),
	'AE': CountryFlag('AE', 'United Arab Emirates', '🇦🇪'),
	'AF': CountryFlag('AF', 'Afghanistan', '🇦🇫'),
	'AG': CountryFlag('AG', 'Antigua & Barbuda', '🇦🇬'),
	'AI': CountryFlag('AI', 'Anguilla', '🇦🇮'),
	'AL': CountryFlag('AL', 'Albania', '🇦🇱'),
	'AM': CountryFlag('AM', 'Armenia', '🇦🇲'),
	'AO': CountryFlag('AO', 'Angola', '🇦🇴'),
	'AQ': CountryFlag('AQ', 'Antarctica', '🇦🇶'),
	'AR': CountryFlag('AR', 'Argentina', '🇦🇷'),
	'AS': CountryFlag('AS', 'American Samoa', '🇦🇸'),
	'AT': CountryFlag('AT', 'Austria', '🇦🇹'),
	'AU': CountryFlag('AU', 'Australia', '🇦🇺'),
	'AW': CountryFlag('AW', 'Aruba', '🇦🇼'),
	'AX': CountryFlag('AX', 'Åland Islands', '🇦🇽'),
	'AZ': CountryFlag('AZ', 'Azerbaijan', '🇦🇿'),
	'BA': CountryFlag('BA', 'Bosnia & Herzegovina', '🇧🇦'),
	'BB': CountryFlag('BB', 'Barbados', '🇧🇧'),
	'BD': CountryFlag('BD', 'Bangladesh', '🇧🇩'),
	'BE': CountryFlag('BE', 'Belgium', '🇧🇪'),
	'BF': CountryFlag('BF', 'Burkina Faso', '🇧🇫'),
	'BG': CountryFlag('BG', 'Bulgaria', '🇧🇬'),
	'BH': CountryFlag('BH', 'Bahrain', '🇧🇭'),
	'BI': CountryFlag('BI', 'Burundi', '🇧🇮'),
	'BJ': CountryFlag('BJ', 'Benin', '🇧🇯'),
	'BL': CountryFlag('BL', 'St. Barthélemy', '🇧🇱'),
	'BM': CountryFlag('BM', 'Bermuda', '🇧🇲'),
	'BN': CountryFlag('BN', 'Brunei', '🇧🇳'),
	'BO': CountryFlag('BO', 'Bolivia', '🇧🇴'),
	'BQ': CountryFlag('BQ', 'Caribbean Netherlands', '🇧🇶'),
	'BR': CountryFlag('BR', 'Brazil', '🇧🇷'),
	'BS': CountryFlag('BS', 'Bahamas', '🇧🇸'),
	'BT': CountryFlag('BT', 'Bhutan', '🇧🇹'),
	'BV': CountryFlag('BV', 'Bouvet Island', '🇧🇻'),
	'BW': CountryFlag('BW', 'Botswana', '🇧🇼'),
	'BY': CountryFlag('BY', 'Belarus', '🇧🇾'),
	'BZ': CountryFlag('BZ', 'Belize', '🇧🇿'),
	'CA': CountryFlag('CA', 'Canada', '🇨🇦'),
	'CC': CountryFlag('CC', 'Cocos (Keeling) Islands', '🇨🇨'),
	'CD': CountryFlag('CD', 'Congo - Kinshasa', '🇨🇩'),
	'CF': CountryFlag('CF', 'Central African Republic', '🇨🇫'),
	'CG': CountryFlag('CG', 'Congo - Brazzaville', '🇨🇬'),
	'CH': CountryFlag('CH', 'Switzerland', '🇨🇭'),
	'CI': CountryFlag('CI', 'Côte d’Ivoire', '🇨🇮'),
	'CK': CountryFlag('CK', 'Cook Islands', '🇨🇰'),
	'CL': CountryFlag('CL', 'Chile', '🇨🇱'),
	'CM': CountryFlag('CM', 'Cameroon', '🇨🇲'),
	'CN': CountryFlag('CN', 'China', '🇨🇳'),
	'CO': CountryFlag('CO', 'Colombia', '🇨🇴'),
	'CP': CountryFlag('CP', 'Clipperton Island', '🇨🇵'),
	'CR': CountryFlag('CR', 'Costa Rica', '🇨🇷'),
	'CU': CountryFlag('CU', 'Cuba', '🇨🇺'),
	'CV': CountryFlag('CV', 'Cape Verde', '🇨🇻'),
	'CW': CountryFlag('CW', 'Curaçao', '🇨🇼'),
	'CX': CountryFlag('CX', 'Christmas Island', '🇨🇽'),
	'CY': CountryFlag('CY', 'Cyprus', '🇨🇾'),
	'CZ': CountryFlag('CZ', 'Czechia', '🇨🇿'),
	'DE': CountryFlag('DE', 'Germany', '🇩🇪'),
	'DG': CountryFlag('DG', 'Diego Garcia', '🇩🇬'),
	'DJ': CountryFlag('DJ', 'Djibouti', '🇩🇯'),
	'DK': CountryFlag('DK', 'Denmark', '🇩🇰'),
	'DM': CountryFlag('DM', 'Dominica', '🇩🇲'),
	'DO': CountryFlag('DO', 'Dominican Republic', '🇩🇴'),
	'DZ': CountryFlag('DZ', 'Algeria', '🇩🇿'),
	'EA': CountryFlag('EA', 'Ceuta & Melilla', '🇪🇦'),
	'EC': CountryFlag('EC', 'Ecuador', '🇪🇨'),
	'EE': CountryFlag('EE', 'Estonia', '🇪🇪'),
	'EG': CountryFlag('EG', 'Egypt', '🇪🇬'),
	'EH': CountryFlag('EH', 'Western Sahara', '🇪🇭'),
	'ER': CountryFlag('ER', 'Eritrea', '🇪🇷'),
	'ES': CountryFlag('ES', 'Spain', '🇪🇸'),
	'ET': CountryFlag('ET', 'Ethiopia', '🇪🇹'),
	'EU': CountryFlag('EU', 'European Union', '🇪🇺'),
	'FI': CountryFlag('FI', 'Finland', '🇫🇮'),
	'FJ': CountryFlag('FJ', 'Fiji', '🇫🇯'),
	'FK': CountryFlag('FK', 'Falkland Islands', '🇫🇰'),
	'FM': CountryFlag('FM', 'Micronesia', '🇫🇲'),
	'FO': CountryFlag('FO', 'Faroe Islands', '🇫🇴'),
	'FR': CountryFlag('FR', 'France', '🇫🇷'),
	'GA': CountryFlag('GA', 'Gabon', '🇬🇦'),
	'GB': CountryFlag('GB', 'United Kingdom', '🇬🇧'),
	'GD': CountryFlag('GD', 'Grenada', '🇬🇩'),
	'GE': CountryFlag('GE', 'Georgia', '🇬🇪'),
	'GF': CountryFlag('GF', 'French Guiana', '🇬🇫'),
	'GG': CountryFlag('GG', 'Guernsey', '🇬🇬'),
	'GH': CountryFlag('GH', 'Ghana', '🇬🇭'),
	'GI': CountryFlag('GI', 'Gibraltar', '🇬🇮'),
	'GL': CountryFlag('GL', 'Greenland', '🇬🇱'),
	'GM': CountryFlag('GM', 'Gambia', '🇬🇲'),
	'GN': CountryFlag('GN', 'Guinea', '🇬🇳'),
	'GP': CountryFlag('GP', 'Guadeloupe', '🇬🇵'),
	'GQ': CountryFlag('GQ', 'Equatorial Guinea', '🇬🇶'),
	'GR': CountryFlag('GR', 'Greece', '🇬🇷'),
	'GS': CountryFlag('GS', 'South Georgia & South Sandwich Islands', '🇬🇸'),
	'GT': CountryFlag('GT', 'Guatemala', '🇬🇹'),
	'GU': CountryFlag('GU', 'Guam', '🇬🇺'),
	'GW': CountryFlag('GW', 'Guinea-Bissau', '🇬🇼'),
	'GY': CountryFlag('GY', 'Guyana', '🇬🇾'),
	'HK': CountryFlag('HK', 'Hong Kong SAR China', '🇭🇰'),
	'HM': CountryFlag('HM', 'Heard & McDonald Islands', '🇭🇲'),
	'HN': CountryFlag('HN', 'Honduras', '🇭🇳'),
	'HR': CountryFlag('HR', 'Croatia', '🇭🇷'),
	'HT': CountryFlag('HT', 'Haiti', '🇭🇹'),
	'HU': CountryFlag('HU', 'Hungary', '🇭🇺'),
	'IC': CountryFlag('IC', 'Canary Islands', '🇮🇨'),
	'ID': CountryFlag('ID', 'Indonesia', '🇮🇩'),
	'IE': CountryFlag('IE', 'Ireland', '🇮🇪'),
	'IL': CountryFlag('IL', 'Israel', '🇮🇱'),
	'IM': CountryFlag('IM', 'Isle of Man', '🇮🇲'),
	'IN': CountryFlag('IN', 'India', '🇮🇳'),
	'IO': CountryFlag('IO', 'British Indian Ocean Territory', '🇮🇴'),
	'IQ': CountryFlag('IQ', 'Iraq', '🇮🇶'),
	'IR': CountryFlag('IR', 'Iran', '🇮🇷'),
	'IS': CountryFlag('IS', 'Iceland', '🇮🇸'),
	'IT': CountryFlag('IT', 'Italy', '🇮🇹'),
	'JE': CountryFlag('JE', 'Jersey', '🇯🇪'),
	'JM': CountryFlag('JM', 'Jamaica', '🇯🇲'),
	'JO': CountryFlag('JO', 'Jordan', '🇯🇴'),
	'JP': CountryFlag('JP', 'Japan', '🇯🇵'),
	'KE': CountryFlag('KE', 'Kenya', '🇰🇪'),
	'KG': CountryFlag('KG', 'Kyrgyzstan', '🇰🇬'),
	'KH': CountryFlag('KH', 'Cambodia', '🇰🇭'),
	'KI': CountryFlag('KI', 'Kiribati', '🇰🇮'),
	'KM': CountryFlag('KM', 'Comoros', '🇰🇲'),
	'KN': CountryFlag('KN', 'St. Kitts & Nevis', '🇰🇳'),
	'KP': CountryFlag('KP', 'North Korea', '🇰🇵'),
	'KR': CountryFlag('KR', 'South Korea', '🇰🇷'),
	'KW': CountryFlag('KW', 'Kuwait', '🇰🇼'),
	'KY': CountryFlag('KY', 'Cayman Islands', '🇰🇾'),
	'KZ': CountryFlag('KZ', 'Kazakhstan', '🇰🇿'),
	'LA': CountryFlag('LA', 'Laos', '🇱🇦'),
	'LB': CountryFlag('LB', 'Lebanon', '🇱🇧'),
	'LC': CountryFlag('LC', 'St. Lucia', '🇱🇨'),
	'LI': CountryFlag('LI', 'Liechtenstein', '🇱🇮'),
	'LK': CountryFlag('LK', 'Sri Lanka', '🇱🇰'),
	'LR': CountryFlag('LR', 'Liberia', '🇱🇷'),
	'LS': CountryFlag('LS', 'Lesotho', '🇱🇸'),
	'LT': CountryFlag('LT', 'Lithuania', '🇱🇹'),
	'LU': CountryFlag('LU', 'Luxembourg', '🇱🇺'),
	'LV': CountryFlag('LV', 'Latvia', '🇱🇻'),
	'LY': CountryFlag('LY', 'Libya', '🇱🇾'),
	'MA': CountryFlag('MA', 'Morocco', '🇲🇦'),
	'MC': CountryFlag('MC', 'Monaco', '🇲🇨'),
	'MD': CountryFlag('MD', 'Moldova', '🇲🇩'),
	'ME': CountryFlag('ME', 'Montenegro', '🇲🇪'),
	'MF': CountryFlag('MF', 'St. Martin', '🇲🇫'),
	'MG': CountryFlag('MG', 'Madagascar', '🇲🇬'),
	'MH': CountryFlag('MH', 'Marshall Islands', '🇲🇭'),
	'MK': CountryFlag('MK', 'North Macedonia', '🇲🇰'),
	'ML': CountryFlag('ML', 'Mali', '🇲🇱'),
	'MM': CountryFlag('MM', 'Myanmar (Burma)', '🇲🇲'),
	'MN': CountryFlag('MN', 'Mongolia', '🇲🇳'),
	'MO': CountryFlag('MO', 'Macao SAR China', '🇲🇴'),
	'MP': CountryFlag('MP', 'Northern Mariana Islands', '🇲🇵'),
	'MQ': CountryFlag('MQ', 'Martinique', '🇲🇶'),
	'MR': CountryFlag('MR', 'Mauritania', '🇲🇷'),
	'MS': CountryFlag('MS', 'Montserrat', '🇲🇸'),
	'MT': CountryFlag('MT', 'Malta', '🇲🇹'),
	'MU': CountryFlag('MU', 'Mauritius', '🇲🇺'),
	'MV': CountryFlag('MV', 'Maldives', '🇲🇻'),
	'MW': CountryFlag('MW', 'Malawi', '🇲🇼'),
	'MX': CountryFlag('MX', 'Mexico', '🇲🇽'),
	'MY': CountryFlag('MY', 'Malaysia', '🇲🇾'),
	'MZ': CountryFlag('MZ', 'Mozambique', '🇲🇿'),
	'NA': CountryFlag('NA', 'Namibia', '🇳🇦'),
	'NC': CountryFlag('NC', 'New Caledonia', '🇳🇨'),
	'NE': CountryFlag('NE', 'Niger', '🇳🇪'),
	'NF': CountryFlag('NF', 'Norfolk Island', '🇳🇫'),
	'NG': CountryFlag('NG', 'Nigeria', '🇳🇬'),
	'NI': CountryFlag('NI', 'Nicaragua', '🇳🇮'),
	'NL': CountryFlag('NL', 'Netherlands', '🇳🇱'),
	'NO': CountryFlag('NO', 'Norway', '🇳🇴'),
	'NP': CountryFlag('NP', 'Nepal', '🇳🇵'),
	'NR': CountryFlag('NR', 'Nauru', '🇳🇷'),
	'NU': CountryFlag('NU', 'Niue', '🇳🇺'),
	'NZ': CountryFlag('NZ', 'New Zealand', '🇳🇿'),
	'OM': CountryFlag('OM', 'Oman', '🇴🇲'),
	'PA': CountryFlag('PA', 'Panama', '🇵🇦'),
	'PE': CountryFlag('PE', 'Peru', '🇵🇪'),
	'PF': CountryFlag('PF', 'French Polynesia', '🇵🇫'),
	'PG': CountryFlag('PG', 'Papua New Guinea', '🇵🇬'),
	'PH': CountryFlag('PH', 'Philippines', '🇵🇭'),
	'PK': CountryFlag('PK', 'Pakistan', '🇵🇰'),
	'PL': CountryFlag('PL', 'Poland', '🇵🇱'),
	'PM': CountryFlag('PM', 'St. Pierre & Miquelon', '🇵🇲'),
	'PN': CountryFlag('PN', 'Pitcairn Islands', '🇵🇳'),
	'PR': CountryFlag('PR', 'Puerto Rico', '🇵🇷'),
	'PS': CountryFlag('PS', 'Palestinian Territories', '🇵🇸'),
	'PT': CountryFlag('PT', 'Portugal', '🇵🇹'),
	'PW': CountryFlag('PW', 'Palau', '🇵🇼'),
	'PY': CountryFlag('PY', 'Paraguay', '🇵🇾'),
	'QA': CountryFlag('QA', 'Qatar', '🇶🇦'),
	'RE': CountryFlag('RE', 'Réunion', '🇷🇪'),
	'RO': CountryFlag('RO', 'Romania', '🇷🇴'),
	'RS': CountryFlag('RS', 'Serbia', '🇷🇸'),
	'RU': CountryFlag('RU', 'Russia', '🇷🇺'),
	'RW': CountryFlag('RW', 'Rwanda', '🇷🇼'),
	'SA': CountryFlag('SA', 'Saudi Arabia', '🇸🇦'),
	'SB': CountryFlag('SB', 'Solomon Islands', '🇸🇧'),
	'SC': CountryFlag('SC', 'Seychelles', '🇸🇨'),
	'SD': CountryFlag('SD', 'Sudan', '🇸🇩'),
	'SE': CountryFlag('SE', 'Sweden', '🇸🇪'),
	'SG': CountryFlag('SG', 'Singapore', '🇸🇬'),
	'SH': CountryFlag('SH', 'St. Helena', '🇸🇭'),
	'SI': CountryFlag('SI', 'Slovenia', '🇸🇮'),
	'SJ': CountryFlag('SJ', 'Svalbard & Jan Mayen', '🇸🇯'),
	'SK': CountryFlag('SK', 'Slovakia', '🇸🇰'),
	'SL': CountryFlag('SL', 'Sierra Leone', '🇸🇱'),
	'SM': CountryFlag('SM', 'San Marino', '🇸🇲'),
	'SN': CountryFlag('SN', 'Senegal', '🇸🇳'),
	'SO': CountryFlag('SO', 'Somalia', '🇸🇴'),
	'SR': CountryFlag('SR', 'Suriname', '🇸🇷'),
	'SS': CountryFlag('SS', 'South Sudan', '🇸🇸'),
	'ST': CountryFlag('ST', 'São Tomé & Príncipe', '🇸🇹'),
	'SV': CountryFlag('SV', 'El Salvador', '🇸🇻'),
	'SX': CountryFlag('SX', 'Sint Maarten', '🇸🇽'),
	'SY': CountryFlag('SY', 'Syria', '🇸🇾'),
	'SZ': CountryFlag('SZ', 'Eswatini', '🇸🇿'),
	'TA': CountryFlag('TA', 'Tristan da Cunha', '🇹🇦'),
	'TC': CountryFlag('TC', 'Turks & Caicos Islands', '🇹🇨'),
	'TD': CountryFlag('TD', 'Chad', '🇹🇩'),
	'TF': CountryFlag('TF', 'French Southern Territories', '🇹🇫'),
	'TG': CountryFlag('TG', 'Togo', '🇹🇬'),
	'TH': CountryFlag('TH', 'Thailand', '🇹🇭'),
	'TJ': CountryFlag('TJ', 'Tajikistan', '🇹🇯'),
	'TK': CountryFlag('TK', 'Tokelau', '🇹🇰'),
	'TL': CountryFlag('TL', 'Timor-Leste', '🇹🇱'),
	'TM': CountryFlag('TM', 'Turkmenistan', '🇹🇲'),
	'TN': CountryFlag('TN', 'Tunisia', '🇹🇳'),
	'TO': CountryFlag('TO', 'Tonga', '🇹🇴'),
	'TR': CountryFlag('TR', 'Turkey', '🇹🇷'),
	'TT': CountryFlag('TT', 'Trinidad & Tobago', '🇹🇹'),
	'TV': CountryFlag('TV', 'Tuvalu', '🇹🇻'),
	'TW': CountryFlag('TW', 'Taiwan', '🇹🇼'),
	'TZ': CountryFlag('TZ', 'Tanzania', '🇹🇿'),
	'UA': CountryFlag('UA', 'Ukraine', '🇺🇦'),
	'UG': CountryFlag('UG', 'Uganda', '🇺🇬'),
	'UM': CountryFlag('UM', 'U.S. Outlying Islands', '🇺🇲'),
	'UN': CountryFlag('UN', 'United Nations', '🇺🇳'),
	'US': CountryFlag('US', 'United States', '🇺🇸'),
	'UY': CountryFlag('UY', 'Uruguay', '🇺🇾'),
	'UZ': CountryFlag('UZ', 'Uzbekistan', '🇺🇿'),
	'VA': CountryFlag('VA', 'Vatican City', '🇻🇦'),
	'VC': CountryFlag('VC', 'St. Vincent & Grenadines', '🇻🇨'),
	'VE': CountryFlag('VE', 'Venezuela', '🇻🇪'),
	'VG': CountryFlag('VG', 'British Virgin Islands', '🇻🇬'),
	'VI': CountryFlag('VI', 'U.S. Virgin Islands', '🇻🇮'),
	'VN': CountryFlag('VN', 'Vietnam', '🇻🇳'),
	'VU': CountryFlag('VU', 'Vanuatu', '🇻🇺'),
	'WF': CountryFlag('WF', 'Wallis & Futuna', '🇼🇫'),
	'WS': CountryFlag('WS', 'Samoa', '🇼🇸'),
	'XK': CountryFlag('XK', 'Kosovo', '🇽🇰'),
	'YE': CountryFlag('YE', 'Yemen', '🇾🇪'),
	'YT': CountryFlag('YT', 'Mayotte', '🇾🇹'),
	'ZA': CountryFlag('ZA', 'South Africa', '🇿🇦'),
	'ZM': CountryFlag('ZM', 'Zambia', '🇿🇲'),
	'ZW': CountryFlag('ZW', 'Zimbabwe', '🇿🇼')
};
