// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoSVsIO4VmCJNBAOFEvXJMjpJ_CX6ruE',
    appId: '1:500583514678:android:d297a3fbce272458018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    storageBucket: 'chan-329813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDezXK1OIMB5e2fhFrchPaDL_bs2fFcIVk',
    appId: '1:500583514678:ios:1f50bb1c217f7c6f018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    storageBucket: 'chan-329813.appspot.com',
    iosClientId: '500583514678-mkce6tt2g3cjf59bblmh3ih30i9rp58r.apps.googleusercontent.com',
    iosBundleId: 'com.moffatman.chan',
  );
}
