// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoSVsIO4VmCJNBAOFEvXJMjpJ_CX6ruE',
    appId: '1:500583514678:android:d297a3fbce272458018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    storageBucket: 'chan-329813.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDezXK1OIMB5e2fhFrchPaDL_bs2fFcIVk',
    appId: '1:500583514678:ios:1f50bb1c217f7c6f018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    storageBucket: 'chan-329813.firebasestorage.app',
    iosBundleId: 'com.moffatman.chan',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCywtjyJ0Nb0lLQYDy_4kK-u3HUYa7C-s',
    appId: '1:500583514678:web:11a05f8d6fa06cba018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    authDomain: 'chan-329813.firebaseapp.com',
    storageBucket: 'chan-329813.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDezXK1OIMB5e2fhFrchPaDL_bs2fFcIVk',
    appId: '1:500583514678:ios:1f50bb1c217f7c6f018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    storageBucket: 'chan-329813.firebasestorage.app',
    iosBundleId: 'com.moffatman.chan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCywtjyJ0Nb0lLQYDy_4kK-u3HUYa7C-s',
    appId: '1:500583514678:web:57be979b0ce4f215018e97',
    messagingSenderId: '500583514678',
    projectId: 'chan-329813',
    authDomain: 'chan-329813.firebaseapp.com',
    storageBucket: 'chan-329813.firebasestorage.app',
  );
}
